[FIX] Override the non-zero exit code on a failed repo sync

diff --git a/.github/workflows/sync_forks.yml b/.github/workflows/sync_forks.yml
--- a/.github/workflows/sync_forks.yml
+++ b/.github/workflows/sync_forks.yml
@@ -53,7 +53,8 @@ jobs:
                 behind_by=$(is_behind $repo)
                 if [ "$behind_by" != "null" ] && [ $behind_by -gt 0 ]; then
                     echo "    Fork $repo is behind by $behind_by commits"
-                    gh repo sync OpenNeuroDatasets-JSONLD/$repo
+                    # Sync the fork and if that fails, prevent the non-zero exit code from crashing the workflow
+                    gh repo sync OpenNeuroDatasets-JSONLD/$repo || true
                 else
                     # echo "Fork $repo is up to date"
                     :
